/*
 *		Econ 850 Problem Sets (James MacKinnon)
 * 

Assignment 2 2016
Q1 2016) Suppose that a time series is generated by the DGP

	yt = b0*y_t-1 + ut,  ut ~ NID(0; sigma^2) (1)

You can either estimate the model

	yt = b*y_t-1 + ut,    t = 1 ... n 		  (2)

which corresponds to the DGP, or the model

	yt = a + b*y_t-1 + ut, t = 1 ... n 		  (3)

which allows for a constant that is not actually in the DGP.

a) Generate at least 1000 simulated samples from (1) with n = 20, b0 = 0.8 and
sigma=4. Note that each sample must have 21 elements, including y0. Explain
how you generated y0 and justify the procedure you used.*/


/*b) For each simulated sample, estimate both model (2) and model (3). Use the
two sets of at least 1000 estimates of  to estimate the bias of each of the
estimators of . Which estimator is more biased? Why do you think this is
the case?*/


/*c) Repeat the experiments of part b) for sample sizes of 40, 80, 160, 320, 640,
1280, and 2560. Do the biases of the two estimators change systematically as
the sample size is increased? Explain.*/


/*d) Using the same simulated samples you generated in parts b) and c), calculate
t statistics for the hypothesis that b=b0 for model (2) and model (3). Report
the fraction of the time that the null hypothesis is rejected at the .05 level for
both models and for all eight sample sizes./*


/*******************************************************************/


/*Assignment 3 2015*/
/*Q1. Suppose you generate n random variables yi from the Chi2(3) distribution. Let ¯y
denote their sample mean.

a) What are the mean (n) and the variance 2(n) of the ¯y? Note that these
quantities are functions of n.*/

%let N = 20;                          
%let NumSamples = 2000;                 

proc iml;


/*b) Generate 2000 values of ¯y, indexed by j, for n = 20. Plot the empirical distribution
function, or EDF, of the ¯yj . On the same axes, plot the CDF of the
normal distribution with mean mu(20) and variance sigma^2(20).*/



/*c) Now generate 2000 values of ¯y for n = 100 and plot the EDF of the ¯yj . On
the same axes, plot the CDF of the normal distribution with mean mu(100) and
variance sigma^2(100).*/



/*d) Finally, generate 2000 values of ¯y for n = 500 and plot the EDF of the ¯yj . On
the same axes, plot the CDF of the normal distribution with mean mu(500) and
variance sigma^2(500)*/



/*e) There exists a transformation f(¯y, n) of ¯y and n that is asymptotically distributed
as N(0, 1). What is this transformation? For the data of parts b)
through d), plot f(¯y, n) on the same axes. What do you conclude?*/


/*******************************************************************/
